eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
server:
  port: 8083
spring:
  application:
    name: Person-Service
ribbon:
  eureka:
    enabled: true