eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
server:
  port: 8093
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PERSON-SERVICE
          uri: lb://PERSON-SERVICE
          predicates:
            - Path=/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/**
